### ISSUE TITLE
I get the following error when sending "pod install"

### ISSUE THREAD

**Issue by kvandake** [Astrocoders/react-native-selectable-text#13]
```
The `react-native-selectable-text` pod failed to validate due to 2 errors:
    - ERROR | attributes: Missing required attribute `homepage`.
    - ERROR | attributes: Missing required attribute `summary`.
```

**Comment by fakenickels** [comment]
Are you installing from the repo or npm?
cc @georgelima

**Comment by kvandake** [comment]
I installed the library from npm.

**Comment by fakenickels** [comment]
Meanwhile we fix this, can you try using the version 1.1.0 or 1.0.0?

**Comment by kvandake** [comment]
Ok, I will try using this versions.

**Comment by fakenickels** [comment]
Still having this issue @kvandake ?

**Comment by fakenickels** [comment]
Hey there, looks like the issue is just related to those infos missing in the podspec 
https://github.com/Astrocoders/react-native-selectable-text/blob/master/react-native-selectable-text.podspec
If you could send a PR would be much appreciated, thanks

**Comment by passerbyloo** [comment]
I also got this error, how you fix that? @kvandake
