### ISSUE TITLE
menuItems without API DEMOS

### ISSUE THREAD

**Issue by nguyendangkhoi** [Astrocoders/react-native-selectable-text#14]
i try run demo with menuItems={["Foo", "Bar"]} but in View build with menuItems Foo Bar and API DEMOS

**Comment by fakenickels** [comment]
Hey there, thanks for the feedback!
Are you running the Android or iOS demo? From the repo?

**Comment by nguyendangkhoi** [comment]
i running with Android Demo, and i dont know how to remove API DEMOS menuItems please support, thankmate

**Comment by akinkoker** [comment]
https://i.imgur.com/WzpzkuK.jpg
what is the solution?

**Comment by fakenickels** [comment]
Hi there! Thanks for testing it. Just to be sure, which branch are you guys in?

**Comment by fakenickels** [comment]
Can you test disabling HMR and just reloading? Have you tried `yarn react-native --reset-cache` after changing?

**Comment by fakenickels** [comment]
If you guys want to debug, we set the menu items to be updated here along with the prop passed via JS https://github.com/Astrocoders/react-native-selectable-text/blob/master/android/src/main/java/com/astrocoders/selectabletext/RNSelectableTextManager.java#L42

**Comment by fakenickels** [comment]
Hey there we just pushed some more fixes, if you guys could test the points I raised above would be much appreciated

**Comment by nguyendangkhoi** [comment]
@akinkoker 
API DEMOS only active when debug with emulator device
