### ISSUE TITLE
[IOS]info ld: library not found for -lRNSelectableText

### ISSUE THREAD

**Issue by zm-john** [Astrocoders/react-native-selectable-text#19]
I have do this:
```
yarn add @astrocoders/react-native-selectable-text
react-native link @astrocoders/react-native-selectable-text
```

when I run `react-native run-android` that is ok.
But when I run `react-native run-ios` have error:
```
info ld: library not found for -lRNSelectableText
```
dependencies:
```
"@astrocoders/react-native-selectable-text": "^1.2.1",
"react-native": "0.59.9",
```

**Comment by fakenickels** [comment]
how is your Podfile?

**Comment by zm-john** [comment]
@fakenickels 
no Podfile.

**Comment by fakenickels** [comment]
@zm-john could you solve your issue?
we highly recommend using it with pods, it's how we are using it right now

**Comment by zm-john** [comment]
@fakenickels thanks. I will try.

**Comment by tobiaseisenschenk** [comment]
I could not install the podfile due to a missing homepage attribute

**Comment by guilhermedecampo** [comment]
@tobiaseisenschenk 	would be awesome if you could copy and past all the error logs and even the commands you ran. So we can have more context of the problems.

**Comment by tobiaseisenschenk** [comment]
@guilhermedecampo I used the podspec in the `/ios` directory, which didn't have a homepage attribute and thus failed. Please have a look at my [PR](https://github.com/Astrocoders/react-native-selectable-text/pull/25) where I made some changes for my usecase.

**Comment by ammoradi** [comment]
@fakenickels can i see your Podfile?
