### ISSUE TITLE
How to change popup's style?

### ISSUE THREAD

**Issue by ammoradi** [Astrocoders/react-native-selectable-text#21]
how I can change the popup's style and the style of texts showing in popups (menu items text style)?

**Comment by guilhermedecampo** [comment]
You don't! It's a hard thing to do. 

If you have some time to work on this we appreciate it!

**Comment by fakenickels** [comment]
Sorry @ammoradi , unfortunately it's not in our scope for this project yet. But we would be glad to see a PR implementing this.
