### ISSUE TITLE
华为手机无效

### ISSUE THREAD

**Issue by ImVeryGood** [Astrocoders/react-native-selectable-text#22]
在华为手机无效，在小米手机设置的menuItems也是无效弹出系统的，

**Comment by guilhermedecampo** [comment]
Translate to English?

**Comment by ImVeryGood** [comment]
use huawei is invalid，and in xiaomi also invalid,I have set  menuItems is useless

**Comment by fakenickels** [comment]
@ImVeryGood have you tried running the demo? Or just directly in your app?

**Comment by guilhermedecampo** [comment]
Close due inactivity.
