### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by huidev** [Astrocoders/react-native-selectable-text#23]
@astrocoders/react-native-selectable-text@1.2.1" has incorrect peer dependency "react-native@^0.41.2"

**Comment by fakenickels** [comment]
This is usually just a warning and you should be able to get it installed just after.
This warning it's caused because https://github.com/Astrocoders/react-native-selectable-text/blob/master/package.json#L16 is outdated, would you mind sending a PR bumping it?
