### ISSUE TITLE
Is there any way of passing HTML code into the value prop?

### ISSUE THREAD

**Issue by Sandmountain** [Astrocoders/react-native-selectable-text#27]
Hello!
First off i'd like to say that this library have saved me from trashing a project that I've been working on, so thank you for sharing! 

I have a question however, and that is, is there any way of passing HTML tags or perhaps another component that can parse the HTML onto the value parameter? 

Thank you in advance!

**Comment by guilhermedecampo** [comment]
Hey @sandmountain unfortunately it's not on the scope of the project and there are some good limitations on iOS for it. 

If you wanna put some effort and create a PR with an alternative you're mostly welcomed!

Thanks
