### ISSUE TITLE
'RCTText/RCTBaseTextInputView.h' file not found

### ISSUE THREAD

**Issue by tuannguyenhoangit** [Astrocoders/react-native-selectable-text#28]
I use option 1 to link library
Version "@astrocoders/react-native-selectable-text": "^1.2.1",

<img width="264" alt="Screen Shot 2019-07-30 at 5 21 22 PM" src="https://user-images.githubusercontent.com/33544470/62121846-ab745800-b2ee-11e9-835f-7849e9640976.png">
<img width="556" alt="Screen Shot 2019-07-30 at 5 21 30 PM" src="https://user-images.githubusercontent.com/33544470/62121859-ae6f4880-b2ee-11e9-8dcf-81e83f8852f3.png">
<img width="797" alt="Screen Shot 2019-07-30 at 5 20 54 PM" src="https://user-images.githubusercontent.com/33544470/62121862-afa07580-b2ee-11e9-86c4-81d6c826715f.png">

**Comment by ulazarevic** [comment]
I'm having the same issue. I don't know if anybody is maintaining this library?

**Comment by ulazarevic** [comment]
@tuannguyenhoangit Did you manage to fix this somehow?

**Comment by killabeeez** [comment]
+1

**Comment by akos-bako** [comment]
I have ran into this issue aswell. The archive failed with no error message, and the Simulator build failed with this error. Luckily the general iOS error fixing routine helped me out.

0. Make sure you linked it properly, I used the same method as you.
1. delete DerivedData
2. Product > Clean ( or CMD + SHIFT + K )
3. close XCode fully
4. ran this script (I use yarn, if you use npm modify it)

watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf $TMPDIR/metro* && rm -rf $TMPDIR/haste-* && rm -rf node_modules && yarn install

5. open XCode and let it finish indexing 

For me this was enough to fix the error.

**Comment by guilhermedecampo** [comment]
Working fine on our projects right @georgelima?

**Comment by fakenickels** [comment]
We recommend using CocoaPods instead of RN linking

**Comment by medson10** [comment]
the latest @tuannguyenhoangit , 1.3.0 https://www.npmjs.com/package/@astrocoders/react-native-selectable-text
