### ISSUE TITLE
onHighlightPress id param is undefined

### ISSUE THREAD

**Issue by renanlucas07** [Astrocoders/react-native-selectable-text#30]
`onHighlightPress={(id) => {										 
   console.log(id);
}}`

the code above returns undefined, i need to get the id of the pressed highlighted text, am i doing something wrong?

**Comment by renanlucas07** [comment]
Found the problem, the mapHighlightsRanges() function wasn't passing the id to the data array it returns

**Comment by fakenickels** [comment]
Thanks for finding about the bug!
Would you mind sending a PR for it?

**Comment by renanlucas07** [comment]
Not at all, will send one this week

**Comment by guilhermedecampo** [comment]
@renanlucas07 lemme know about the PR for this.

**Comment by fakenickels** [comment]
Already fixed https://github.com/Astrocoders/react-native-selectable-text/blob/master/Demo/SelectableText.js#L117
