### ISSUE TITLE
Android 9 recognises the selected content and overrides the menuItems with options that will cause crashes

### ISSUE THREAD

**Issue by akos-bako** [Astrocoders/react-native-selectable-text#31]
The Library works really well on Android 9.0 and below and when selecting normal text on Android 9.0. But as soon as I select a phone number or email address the content is recognised by the OS and it overrides the menu items. The new options are related to the recognised content. Is there a way to stop this from happening? Now it crashes on every single new option provided by the OS.

### Logcat:

> 08-30 17:11:14.294  7061  7061 E AndroidRuntime: FATAL EXCEPTION: main
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime: Process: MY.PACKAGE.NAME, PID: 7061
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=1; index=16908353
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at com.astrocoders.selectabletext.RNSelectableTextManager$1.onActionItemClicked(RNSelectableTextManager.java:85)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:4318)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2647)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:101)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:776)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:161)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:923)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:913)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0(FloatingActionMode.java:126)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at com.android.internal.view.-$$Lambda$FloatingActionMode$LU5MpPuKYDtwlFAuYhXYfzgLNLE.onMenuItemClick(Unknown Source:2)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$2.onClick(FloatingToolbar.java:512)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at android.view.View.performClick(View.java:6653)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:6625)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at android.view.View.access$3100(View.java:786)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:26223)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:891)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7470)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
> 08-30 17:11:14.294  7061  7061 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

### My react native code for the package

```
          <SelectableText
            value={data.text}
            onSelection={this.onMenuItemSelected}
            menuItems={"Copy"}
          />
```

###Tested on:

OnePlus 3T, Android 9.0 (Crashes)
Huawei Honor 10, Android 9.0 (Crashes)
Samsung Galaxy A5 Android 8.0 (Works)

```
    "react": "16.8.3",
    "react-native": "0.59.5",
```

**Comment by guilhermedecampo** [comment]
Thanks for the review and testing on devices @akos-bako. We're fully open to PRs to fix these issues.

**Comment by guilhermedecampo** [comment]
Could you fix this @akos-bako?

**Comment by akos-bako** [comment]
Yea, I did. I've sent a PR and it got accepted. Would be nice to have it released with a new version tho.
