### ISSUE TITLE
How can i use this in a webview 

### ISSUE THREAD

**Issue by mahdidavoodi7** [Astrocoders/react-native-selectable-text#33]
I have a webview and i wanted to user can't copy a text from it so i have to change the selected text tooltip.

can you help me figure it out ?

**Comment by guilhermedecampo** [comment]
hmm you don't @mahdidavoodi7. We are using the OS components to render the selectable-text.

**Comment by mahdidavoodi7** [comment]
@guilhermedecampo Do you have any clue what should i do ?

**Comment by guilhermedecampo** [comment]
you'll need to work on webview internals. Pretty harsh I think. 

if you find out another way, please let us know.

**Comment by mahdidavoodi7** [comment]
Sure, Thanks

**Comment by fakenickels** [comment]
Unfortunately it does not have support for webview
