### ISSUE TITLE
NPM package is behind GitHub latest

### ISSUE THREAD

**Issue by mahedihs1997** [Astrocoders/react-native-selectable-text#35]
Hi, I've just tried to install via npm. When I do `react-native-selectable-text.podspec` file contains `"https://github.com/react-native-community/react-native-slider.git"` instead of `react-native-selectable-text`. 

Should I try install a different version? Or does the package need a new NPM release?

**Comment by fakenickels** [comment]
@medson10

**Comment by DerrickC** [comment]
Same problem! Waiting for the new version!

**Comment by medson10** [comment]
Hi, sorry for the delay, just published https://www.npmjs.com/package/@astrocoders/react-native-selectable-text/v/1.3.0
