### ISSUE TITLE
iOS 13 Fucked up this package

### ISSUE THREAD

**Issue by guilhermedecampo** [Astrocoders/react-native-selectable-text#36]
🤷‍♂

**Comment by fakenickels** [comment]
Sorry sir, this is an open source project. You shouldn't use this language.

**Comment by fakenickels** [comment]
Gonna ban you

**Comment by fakenickels** [comment]
gotta go fast

**Comment by guilhermedecampo** [comment]
True Story Sir. 


Now it's only possible to select a word and if I try to use the cursor on the edges on the selected word it removes the selected from the text. 

https://cdn.discordapp.com/attachments/169473922381774848/626109661824942110/clip.MP4

**Comment by fakenickels** [comment]
Thanks for your report, Sir.
We'll be looking into that.
Have a good day, Sir.

**Comment by guilhermedecampo** [comment]
AMAZING REPORT SYSTEM. 

Thank you, Sir. 

Hopefully, you guys make something about it because our app is not launching because of this.

**Comment by fakenickels** [comment]
Thanks sir, if this has been helpful to you don't hesitate to donate to our Bitcoin wallet

**Comment by guilhermedecampo** [comment]
Once this problem is solved we can discuss recompensation.

Right now I'm just gonna await you guys do your job and maintain it.

**Comment by fakenickels** [comment]
Ban

**Comment by mohamed-aleem** [comment]
Unfort. I think this issue still exist @fakenickels

**Comment by jonasfrid** [comment]
This is still an issue. Works fine on Android, but iOS only allows us to select one word at a time, unless you tap + press and move the finger real quick. No chance at changing the selection once set, though.

**Comment by jonasfrid** [comment]
@guilhermedecampo did you find a workaround?
