### ISSUE TITLE
How to show an  image instead of Text (like- Highlited, underline)?

### ISSUE THREAD

**Issue by PradeepLinkites** [Astrocoders/react-native-selectable-text#43]
Please provide the resolution on this issue

**Comment by guilhermedecampo** [comment]
Explain better @PradeepLinkites. 
Best with examples and images.

**Comment by PradeepLinkites** [comment]
![images](https://user-images.githubusercontent.com/47211749/71232381-c5ebb400-2317-11ea-899e-b0fac7cce46e.png)

@guilhermedecampo ,PFA for your reference ,in this attached images once we select the text we are getting text string( Highlighted) by menuItems.it is possible to show instead of this string ?

**Comment by PradeepLinkites** [comment]
![images](https://user-images.githubusercontent.com/47211749/71232761-452db780-2319-11ea-965b-4e61dba28665.png)

@guilhermedecampo ,PFA for your reference ,in this attached images once we select the text we are getting text string( Highlighted) by menuItems.it is possible to show instead of this string ?
