### ISSUE TITLE
Only possible to select one word at a time on iOS

### ISSUE THREAD

**Issue by jonasfrid** [Astrocoders/react-native-selectable-text#48]
Selection almost works fine in the iOS emulator, with the one exception that it isn't possible to pull the selection handles to change the selection once it's there. The only way to select multiple words is to press and drag.

On the device (iOS), it is impossible to select multiple words by pressing and dragging. The selection moves, but stays on maximum one word, unless you quickly tap + press real quick, which is unintuitive and still pretty difficult to achieve. And it is impossible to pull the selection handles here, either.

Any idea what's going wrong?

**Comment by mohamed-aleem** [comment]
hi @jonasfrid i just made a pull request with a fix for this issue on iOS #50 
@fakenickels  pls review and merge when you get a chance and the fix works for you 

i think this issue is related as well #36

**Comment by jonasfrid** [comment]
Many thanks, @mohamed-aleem and @fakenickels! I noticed this is now merged to master, but not yet published to npmjs (latest version 1.3.0), any chance of landing it there soon as well?

**Comment by georgelima** [comment]
Published @jonasfrid https://github.com/Astrocoders/react-native-selectable-text/commit/ef1a646b858cfeb042feaca490e36b76728de71a! Thanks all!
