### ISSUE TITLE
Dragging selection handles not working on iOS 13.5

### ISSUE THREAD

**Issue by nsantacruz** [Astrocoders/react-native-selectable-text#56]
This issue is following up on the conversation in @mohamed-aleem's PR #50 . 

## Description

This issue seems to be only affecting iOS 13.5. Other versions of iOS and all versions of Android seem fine. After long-pressing to select a word, you cannot update your selection with the handles. Trying to drag the handles causes the selection to dissapear.

## Version

This is seen in v1.4.0 of this package and iOS 13.5 (both simulator and real device)

## Expected Behavior

After long-pressing to select a word, you should be able to drag the selection handles to update your selection

**Comment by jaroslawkrol** [comment]
@nsantacruz Bug is resolved in version 1.5.0 #50 

Tested on real device and simulator (iOS 13.5)

**Comment by nsantacruz** [comment]
@jaroslawkrol didn't see that. thanks!

**Comment by mohamed-aleem** [comment]
glad to hear that @nsantacruz @jaroslawkrol, keep it up,  and my apologies for the late response, was really busy with some gigs the last week and didn't get a chance to look into it.
